version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_DB: "sMudi_GXDB" # Replace with your desired database name
      POSTGRES_USER: "sMudi_GXU" # Replace with your desired username
      POSTGRES_PASSWORD: "sMudi_GXP" # Replace with your desired password
    ports:
      - "5432:5432" # Map the PostgreSQL default port
    volumes:
      - ./pg_data:/var/lib/postgresql/data # Store data persistently

# Add any other services or configurations as needed
