version: "3.9"
services:
  postgres:
    user: root
    restart: unless-stopped
    container_name: postgres
    ports:
      - target: 5432
        published: 32974
    image: timescale/timescaledb-ha:pg15-all
    environment:
      POSTGRES_DB: adiq
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-root}"
    volumes:
      - ./_DATA/postgres-ha:/home/postgres/pgdata/data:rw
    networks:
      - adiq

  metabase-postgres:
    user: root
    restart: unless-stopped
    container_name: metabase-postgres
    ports:
      - target: 5432
        published: 32975
    image: timescale/timescaledb-ha:pg15-all
    environment:
      POSTGRES_DB: metabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "${METABASE_POSTGRES_PASSWORD:-root}"
    volumes:
      - ./_DATA/metabase-postgres-ha:/home/postgres/pgdata/data:rw
    networks:
      - adiq
networks:
  adiq:
    name: adiq
    external: true
