version: "3.9"
services:
  postgres:
    user: root
    restart: unless-stopped
    container_name: postgres
    ports:
      - target: 5432
        published: 32974
    image: timescale/timescaledb-ha:pg15-all
    environment:
      POSTGRES_DB: sMudi_GXDB
      POSTGRES_USER: sMudi_GXU
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-sMudi_GXP}"
    volumes:
      - ./_DATA/postgres-ha:/home/postgres/pgdata/data:rw
    networks:
      - smudi

networks:
  adiq:
    name: smudi
    external: true
