version: "3"
services:
  postgres:
    user: root
    container_name: smudi-postgres
    ports:
      - target: 5432
        published: 5432
    image: timescale/timescaledb-ha:pg15-all
    environment:
      POSTGRES_DB: sMudi_GXDB
      POSTGRES_USER: sMudi_GXU
      POSTGRES_PASSWORD: sMudi_GXP
    volumes:
      - ./infra/postgres/TMP-WD/:/wd/
      - ./_DATA/postgres-ha:/home/postgres/pgdata/data:rw
